// <auto-generated />
using System;
using ChatLake.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatLake.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChatLakeDbContext))]
    [Migration("20260106222316_BlogSuggestion_ContentGeneration")]
    partial class BlogSuggestion_ContentGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.Conversation", b =>
                {
                    b.Property<long>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConversationId"));

                    b.Property<byte[]>("ConversationKey")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedFromImportBatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalConversationId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FirstMessageAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMessageAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConversationId");

                    b.HasIndex("ConversationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Conversation_ConversationKey");

                    b.HasIndex("CreatedFromImportBatchId")
                        .HasDatabaseName("IX_Conversation_CreatedFromImportBatchId");

                    b.ToTable("Conversation", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.ConversationArtifactMap", b =>
                {
                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<long>("RawArtifactId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("MappedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversationId", "RawArtifactId");

                    b.HasIndex("RawArtifactId")
                        .HasDatabaseName("IX_ConversationArtifactMap_RawArtifactId");

                    b.ToTable("ConversationArtifactMap", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.ConversationSegment", b =>
                {
                    b.Property<long>("ConversationSegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConversationSegmentId"));

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndMessageIndex")
                        .HasColumnType("int");

                    b.Property<long>("InferenceRunId")
                        .HasColumnType("bigint");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("int");

                    b.Property<int>("StartMessageIndex")
                        .HasColumnType("int");

                    b.HasKey("ConversationSegmentId");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_ConversationSegment_ConversationId");

                    b.HasIndex("InferenceRunId")
                        .HasDatabaseName("IX_ConversationSegment_InferenceRunId");

                    b.HasIndex("ConversationId", "SegmentIndex")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConversationSegment_Position");

                    b.ToTable("ConversationSegment", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MessageTimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("RawArtifactId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SequenceIndex")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_Message_ConversationId");

                    b.HasIndex("RawArtifactId")
                        .HasDatabaseName("IX_Message_RawArtifactId");

                    b.HasIndex("ConversationId", "Role", "SequenceIndex", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("UX_Message_Conversation_Role_Sequence_ContentHash");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.ParsingFailure", b =>
                {
                    b.Property<long>("ParsingFailureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ParsingFailureId"));

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("RawArtifactId")
                        .HasColumnType("bigint");

                    b.HasKey("ParsingFailureId");

                    b.HasIndex("RawArtifactId")
                        .HasDatabaseName("IX_ParsingFailure_RawArtifactId");

                    b.ToTable("ParsingFailure", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.BlogTopicSuggestion", b =>
                {
                    b.Property<long>("BlogTopicSuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BlogTopicSuggestionId"));

                    b.Property<string>("BlogContentMarkdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("EvaluationScoreJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("InferenceRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("OutlineJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProjectSuggestionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceConversationIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceSegmentIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("BlogTopicSuggestionId");

                    b.HasIndex("Confidence")
                        .HasDatabaseName("IX_BlogTopicSuggestion_Confidence");

                    b.HasIndex("InferenceRunId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectSuggestionId")
                        .HasDatabaseName("IX_BlogTopicSuggestion_ProjectSuggestionId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_BlogTopicSuggestion_Status");

                    b.ToTable("BlogTopicSuggestion", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.ConversationSimilarity", b =>
                {
                    b.Property<long>("ConversationSimilarityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConversationSimilarityId"));

                    b.Property<long>("ConversationIdA")
                        .HasColumnType("bigint");

                    b.Property<long>("ConversationIdB")
                        .HasColumnType("bigint");

                    b.Property<long>("InferenceRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Similarity")
                        .HasColumnType("decimal(7,6)");

                    b.HasKey("ConversationSimilarityId");

                    b.HasIndex("ConversationIdA")
                        .HasDatabaseName("IX_ConversationSimilarity_A");

                    b.HasIndex("ConversationIdB")
                        .HasDatabaseName("IX_ConversationSimilarity_B");

                    b.HasIndex("Similarity")
                        .HasDatabaseName("IX_ConversationSimilarity_Value");

                    b.HasIndex("InferenceRunId", "ConversationIdA", "ConversationIdB")
                        .IsUnique()
                        .HasDatabaseName("UQ_ConversationSimilarity_Pair");

                    b.ToTable("ConversationSimilarity", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.ConversationTopic", b =>
                {
                    b.Property<long>("ConversationTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConversationTopicId"));

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<long>("InferenceRunId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(7,6)");

                    b.Property<long>("TopicId")
                        .HasColumnType("bigint");

                    b.HasKey("ConversationTopicId");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_ConversationTopic_ConversationId");

                    b.HasIndex("InferenceRunId");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("IX_ConversationTopic_TopicId");

                    b.ToTable("ConversationTopic", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.InferenceRun", b =>
                {
                    b.Property<long>("InferenceRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InferenceRunId"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FeatureConfigHashSha256")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("InputDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("InputScope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InferenceRunId");

                    b.HasIndex("RunType")
                        .HasDatabaseName("IX_InferenceRun_RunType");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("IX_InferenceRun_StartedAtUtc");

                    b.ToTable("InferenceRun", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.ProjectDriftMetric", b =>
                {
                    b.Property<long>("ProjectDriftMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProjectDriftMetricId"));

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DriftScore")
                        .HasColumnType("decimal(7,6)");

                    b.Property<long>("InferenceRunId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("WindowEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WindowStartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectDriftMetricId");

                    b.HasIndex("InferenceRunId");

                    b.HasIndex("ProjectId", "WindowStartUtc")
                        .HasDatabaseName("IX_ProjectDriftMetric_Project_Window");

                    b.ToTable("ProjectDriftMetric", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.ProjectSuggestion", b =>
                {
                    b.Property<long>("ProjectSuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProjectSuggestionId"));

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ConversationIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("InferenceRunId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ResolvedProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("SegmentIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SuggestedName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SuggestedProjectKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UniqueConversationCount")
                        .HasColumnType("int");

                    b.HasKey("ProjectSuggestionId");

                    b.HasIndex("Confidence")
                        .HasDatabaseName("IX_ProjectSuggestion_Confidence");

                    b.HasIndex("InferenceRunId");

                    b.HasIndex("ResolvedProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ProjectSuggestion_Status");

                    b.ToTable("ProjectSuggestion", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.SegmentEmbedding", b =>
                {
                    b.Property<long>("SegmentEmbeddingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SegmentEmbeddingId"));

                    b.Property<long>("ConversationSegmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dimensions")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("EmbeddingVector")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("InferenceRunId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("SourceContentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.HasKey("SegmentEmbeddingId");

                    b.HasIndex("InferenceRunId")
                        .HasDatabaseName("IX_SegmentEmbedding_InferenceRunId");

                    b.HasIndex("ConversationSegmentId", "EmbeddingModel")
                        .IsUnique()
                        .HasDatabaseName("UQ_SegmentEmbedding_Segment_Model");

                    b.ToTable("SegmentEmbedding", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.Topic", b =>
                {
                    b.Property<long>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TopicId"));

                    b.Property<long>("InferenceRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("KeywordsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TopicId");

                    b.HasIndex("InferenceRunId")
                        .HasDatabaseName("IX_Topic_InferenceRunId");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.UserOverride", b =>
                {
                    b.Property<long>("UserOverrideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserOverrideId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OverrideType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserOverrideId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_UserOverride_CreatedAtUtc");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("IX_UserOverride_Target");

                    b.ToTable("UserOverride", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Importing.Entities.ImportBatch", b =>
                {
                    b.Property<long>("ImportBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImportBatchId"));

                    b.Property<int>("ArtifactCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImportLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessedConversationCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TotalConversationCount")
                        .HasColumnType("int");

                    b.HasKey("ImportBatchId");

                    b.HasIndex("ImportedAtUtc")
                        .HasDatabaseName("IX_ImportBatch_ImportedAtUtc");

                    b.ToTable("ImportBatch", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Importing.Entities.RawArtifact", b =>
                {
                    b.Property<long>("RawArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RawArtifactId"));

                    b.Property<string>("ArtifactName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ImportBatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("StoredPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RawArtifactId");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("IX_RawArtifact_ImportBatchId");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("IX_RawArtifact_Sha256");

                    b.ToTable("RawArtifact", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Projects.Entities.ConversationSummary", b =>
                {
                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FirstMessageAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMessageAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<string>("ParticipantSet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PreviewText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversationId");

                    b.ToTable("ConversationSummary", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Projects.Entities.Project", b =>
                {
                    b.Property<long>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProjectId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_Project_ProjectKey");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Projects.Entities.ProjectConversation", b =>
                {
                    b.Property<long>("ProjectConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProjectConversationId"));

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InferenceRunId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.HasKey("ProjectConversationId");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_ProjectConversation_ConversationId");

                    b.HasIndex("InferenceRunId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_ProjectConversation_ProjectId");

                    b.HasIndex("ProjectId", "ConversationId", "IsCurrent")
                        .IsUnique()
                        .HasDatabaseName("UQ_ProjectConversation_Current")
                        .HasFilter("[IsCurrent] = 1");

                    b.ToTable("ProjectConversation", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.Conversation", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Importing.Entities.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("CreatedFromImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.ConversationArtifactMap", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Conversations.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatLake.Infrastructure.Importing.Entities.RawArtifact", null)
                        .WithMany()
                        .HasForeignKey("RawArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.ConversationSegment", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Conversations.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatLake.Infrastructure.Gold.Entities.InferenceRun", "InferenceRun")
                        .WithMany()
                        .HasForeignKey("InferenceRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InferenceRun");
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.Message", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Conversations.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatLake.Infrastructure.Importing.Entities.RawArtifact", null)
                        .WithMany()
                        .HasForeignKey("RawArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.ParsingFailure", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Importing.Entities.RawArtifact", null)
                        .WithMany()
                        .HasForeignKey("RawArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.BlogTopicSuggestion", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Gold.Entities.InferenceRun", "InferenceRun")
                        .WithMany()
                        .HasForeignKey("InferenceRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatLake.Infrastructure.Projects.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChatLake.Infrastructure.Gold.Entities.ProjectSuggestion", "ProjectSuggestion")
                        .WithMany()
                        .HasForeignKey("ProjectSuggestionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InferenceRun");

                    b.Navigation("Project");

                    b.Navigation("ProjectSuggestion");
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.ConversationSimilarity", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Gold.Entities.InferenceRun", "InferenceRun")
                        .WithMany()
                        .HasForeignKey("InferenceRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InferenceRun");
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.ConversationTopic", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Gold.Entities.InferenceRun", "InferenceRun")
                        .WithMany()
                        .HasForeignKey("InferenceRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatLake.Infrastructure.Gold.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InferenceRun");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.ProjectDriftMetric", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Gold.Entities.InferenceRun", "InferenceRun")
                        .WithMany()
                        .HasForeignKey("InferenceRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatLake.Infrastructure.Projects.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InferenceRun");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.ProjectSuggestion", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Gold.Entities.InferenceRun", "InferenceRun")
                        .WithMany()
                        .HasForeignKey("InferenceRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatLake.Infrastructure.Projects.Entities.Project", "ResolvedProject")
                        .WithMany()
                        .HasForeignKey("ResolvedProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InferenceRun");

                    b.Navigation("ResolvedProject");
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.SegmentEmbedding", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Conversations.Entities.ConversationSegment", "ConversationSegment")
                        .WithMany()
                        .HasForeignKey("ConversationSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatLake.Infrastructure.Gold.Entities.InferenceRun", "InferenceRun")
                        .WithMany()
                        .HasForeignKey("InferenceRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConversationSegment");

                    b.Navigation("InferenceRun");
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Gold.Entities.Topic", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Gold.Entities.InferenceRun", "InferenceRun")
                        .WithMany()
                        .HasForeignKey("InferenceRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InferenceRun");
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Importing.Entities.RawArtifact", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Importing.Entities.ImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Projects.Entities.ConversationSummary", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Conversations.Entities.Conversation", null)
                        .WithOne()
                        .HasForeignKey("ChatLake.Infrastructure.Projects.Entities.ConversationSummary", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Projects.Entities.ProjectConversation", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Conversations.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatLake.Infrastructure.Gold.Entities.InferenceRun", "InferenceRun")
                        .WithMany()
                        .HasForeignKey("InferenceRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChatLake.Infrastructure.Projects.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InferenceRun");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
