// <auto-generated />
using System;
using ChatLake.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatLake.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChatLakeDbContext))]
    [Migration("20260103140842_Silver_Initial")]
    partial class Silver_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.Conversation", b =>
                {
                    b.Property<long>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConversationId"));

                    b.Property<byte[]>("ConversationKey")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedFromImportBatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalConversationId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FirstMessageAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMessageAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConversationId");

                    b.HasIndex("ConversationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Conversation_ConversationKey");

                    b.HasIndex("CreatedFromImportBatchId")
                        .HasDatabaseName("IX_Conversation_CreatedFromImportBatchId");

                    b.ToTable("Conversation", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.ConversationArtifactMap", b =>
                {
                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<long>("RawArtifactId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("MappedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversationId", "RawArtifactId");

                    b.HasIndex("RawArtifactId")
                        .HasDatabaseName("IX_ConversationArtifactMap_RawArtifactId");

                    b.ToTable("ConversationArtifactMap", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MessageTimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("RawArtifactId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SequenceIndex")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_Message_ConversationId");

                    b.HasIndex("RawArtifactId")
                        .HasDatabaseName("IX_Message_RawArtifactId");

                    b.HasIndex("ConversationId", "Role", "SequenceIndex", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("UX_Message_Conversation_Role_Sequence_ContentHash");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.ParsingFailure", b =>
                {
                    b.Property<long>("ParsingFailureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ParsingFailureId"));

                    b.Property<string>("FailureMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("RawArtifactId")
                        .HasColumnType("bigint");

                    b.HasKey("ParsingFailureId");

                    b.HasIndex("RawArtifactId")
                        .HasDatabaseName("IX_ParsingFailure_RawArtifactId");

                    b.ToTable("ParsingFailure", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Importing.Entities.ImportBatch", b =>
                {
                    b.Property<long>("ImportBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImportBatchId"));

                    b.Property<int>("ArtifactCount")
                        .HasColumnType("int");

                    b.Property<string>("ImportLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ImportBatchId");

                    b.HasIndex("ImportedAtUtc")
                        .HasDatabaseName("IX_ImportBatch_ImportedAtUtc");

                    b.ToTable("ImportBatch", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Importing.Entities.RawArtifact", b =>
                {
                    b.Property<long>("RawArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RawArtifactId"));

                    b.Property<string>("ArtifactName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ImportBatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("StoredPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RawArtifactId");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("IX_RawArtifact_ImportBatchId");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("IX_RawArtifact_Sha256");

                    b.ToTable("RawArtifact", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.Conversation", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Importing.Entities.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("CreatedFromImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.ConversationArtifactMap", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Conversations.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatLake.Infrastructure.Importing.Entities.RawArtifact", null)
                        .WithMany()
                        .HasForeignKey("RawArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.Message", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Conversations.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatLake.Infrastructure.Importing.Entities.RawArtifact", null)
                        .WithMany()
                        .HasForeignKey("RawArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Conversations.Entities.ParsingFailure", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Importing.Entities.RawArtifact", null)
                        .WithMany()
                        .HasForeignKey("RawArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Importing.Entities.RawArtifact", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Importing.Entities.ImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });
#pragma warning restore 612, 618
        }
    }
}
