// <auto-generated />
using System;
using ChatLake.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatLake.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChatLakeDbContext))]
    partial class ChatLakeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatLake.Infrastructure.Importing.Entities.ImportBatch", b =>
                {
                    b.Property<long>("ImportBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImportBatchId"));

                    b.Property<int>("ArtifactCount")
                        .HasColumnType("int");

                    b.Property<string>("ImportLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ImportBatchId");

                    b.HasIndex("ImportedAtUtc")
                        .HasDatabaseName("IX_ImportBatch_ImportedAtUtc");

                    b.ToTable("ImportBatch", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Importing.Entities.RawArtifact", b =>
                {
                    b.Property<long>("RawArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RawArtifactId"));

                    b.Property<string>("ArtifactName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ImportBatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("StoredPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RawArtifactId");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("IX_RawArtifact_ImportBatchId");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("IX_RawArtifact_Sha256");

                    b.ToTable("RawArtifact", (string)null);
                });

            modelBuilder.Entity("ChatLake.Infrastructure.Importing.Entities.RawArtifact", b =>
                {
                    b.HasOne("ChatLake.Infrastructure.Importing.Entities.ImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });
#pragma warning restore 612, 618
        }
    }
}
